apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
  namespace: dev
  labels:
    app: dm
spec:
  replicas: 10
  selector:
    matchLabels:
      app: dm
  template:
    metadata:
      labels:
        app: dm
    spec:
      containers:
      - name: cont-1
        image: shammu101/dm
        ports:
        - containerPort: 80
